import { StyleSheet } from 'react-native';
import { tokens } from '../constants/tokens';


export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: tokens.colors.background,
  },
  topGradient: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 200,
    opacity: 0.15,
  },
  bottomGradient: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: 200,
    opacity: 0.15,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingTop: 60,
    paddingBottom: 140,
  },
  header: {
    marginBottom: 24,
  },
  title: {
    fontSize: 28,
    fontWeight: '700',
    color: tokens.colors.foreground,
    marginBottom: 12,
    textAlign: 'center',
  },
  subtitle: {
    fontSize: 15,
    color: tokens.colors.mutedForeground,
    lineHeight: 22,
    textAlign: 'center',
  },
  progressContainer: {
    marginBottom: 32,
    alignItems: 'center',
  },
  progressBar: {
    width: '100%',
    height: 4,
    backgroundColor: tokens.colors.muted,
    borderRadius: tokens.radius.full,
    overflow: 'hidden',
    marginBottom: 8,
  },
  progressFill: {
    height: '100%',
    backgroundColor: tokens.colors.primary,
    borderRadius: tokens.radius.full,
  },
  progressText: {
    fontSize: 12,
    fontWeight: '600',
    color: tokens.colors.primary,
  },
  section: {
    marginBottom: 32,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 16,
  },
  iconContainer: {
    width: 36,
    height: 36,
    borderRadius: tokens.radius.full,
    backgroundColor: tokens.colors.primary + '15',
    justifyContent: 'center',
    alignItems: 'center',
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: tokens.colors.foreground,
  },
  textInput: {
    height: 56,
    paddingHorizontal: 18,
    backgroundColor: tokens.colors.card,
    borderRadius: tokens.radius.lg,
    borderWidth: 1.5,
    borderColor: tokens.colors.border,
    fontSize: 16,
    color: tokens.colors.foreground,
    marginBottom: 8,
  },
  helpText: {
    fontSize: 13,
    color: tokens.colors.mutedForeground,
    lineHeight: 18,
  },
  experienceGrid: {
    gap: 12,
  },
  experienceCard: {
    padding: 16,
    backgroundColor: tokens.colors.card,
    borderRadius: tokens.radius.lg,
    borderWidth: 1.5,
    borderColor: tokens.colors.border,
  },
  experienceCardSelected: {
    backgroundColor: tokens.colors.primary + '10',
    borderColor: tokens.colors.primary,
  },
  experienceHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  experienceLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: tokens.colors.foreground,
  },
  experienceLabelSelected: {
    color: tokens.colors.primary,
  },
  experienceDescription: {
    fontSize: 14,
    color: tokens.colors.mutedForeground,
    lineHeight: 20,
  },
  experienceDescriptionSelected: {
    color: tokens.colors.foreground,
  },
  checkCircle: {
    width: 24,
    height: 24,
    borderRadius: tokens.radius.full,
    backgroundColor: tokens.colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  countContainer: {
    marginBottom: 20,
    alignItems: 'center',
  },
  countText: {
    fontSize: 14,
    fontWeight: '600',
    color: tokens.colors.primary,
    marginBottom: 4,
  },
  maxReachedText: {
    fontSize: 12,
    color: tokens.colors.warning,
  },
  interestsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 32,
  },
  interestChip: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: tokens.radius.full,
    backgroundColor: tokens.colors.secondary + '15',
    borderWidth: 1.5,
    borderColor: 'transparent',
    gap: 6,
  },
  interestChipSelected: {
    backgroundColor: tokens.colors.primary,
    borderColor: tokens.colors.primary,
  },
  interestChipDisabled: {
    opacity: 0.4,
  },
  interestText: {
    fontSize: 14,
    fontWeight: '500',
    color: tokens.colors.foreground,
  },
  interestTextSelected: {
    color: tokens.colors.primaryForeground,
    fontWeight: '600',
  },
  interestTextDisabled: {
    color: tokens.colors.mutedForeground,
  },
  checkMark: {
    width: 18,
    height: 18,
    borderRadius: tokens.radius.full,
    backgroundColor: tokens.colors.primaryForeground + '25',
    alignItems: 'center',
    justifyContent: 'center',
  },
  customInterestContainer: {
    marginBottom: 24,
  },
  customInterestLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: tokens.colors.foreground,
    marginBottom: 12,
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 8,
  },
  input: {
    flex: 1,
    height: 48,
    paddingHorizontal: 16,
    backgroundColor: tokens.colors.card,
    borderRadius: tokens.radius.md,
    borderWidth: 1.5,
    borderColor: tokens.colors.border,
    fontSize: 15,
    color: tokens.colors.foreground,
  },
  addButton: {
    height: 48,
    paddingHorizontal: 20,
    backgroundColor: tokens.colors.primary,
    borderRadius: tokens.radius.md,
    alignItems: 'center',
    justifyContent: 'center',
  },
  addButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: tokens.colors.primaryForeground,
  },
  remainingText: {
    fontSize: 12,
    color: tokens.colors.mutedForeground,
    fontStyle: 'italic',
  },
  customInterestsList: {
    marginBottom: 24,
  },
  customInterestsLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: tokens.colors.foreground,
    marginBottom: 12,
  },
  customInterestsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 16,
  },
  customInterestChip: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: tokens.radius.full,
    backgroundColor: tokens.colors.primary + '10',
    borderWidth: 1.5,
    borderColor: tokens.colors.primary,
    gap: 6,
  },
  customGoalChip: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: tokens.radius.full,
    backgroundColor: tokens.colors.primary,
    borderWidth: 1.5,
    borderColor: tokens.colors.primary,
    gap: 6,
  },
  customInterestText: {
    fontSize: 14,
    fontWeight: '500',
    color: tokens.colors.primary,
  },
  customGoalText: {
    fontSize: 14,
    fontWeight: '500',
    color: tokens.colors.primaryForeground,
  },
  customCheckMark: {
    width: 18,
    height: 18,
    borderRadius: tokens.radius.full,
    backgroundColor: tokens.colors.primaryForeground + '25',
    alignItems: 'center',
    justifyContent: 'center',
  },
  customInterestsHint: {
    fontSize: 12,
    color: tokens.colors.mutedForeground,
    fontStyle: 'italic',
  },
  presetInterestsContainer: {
    marginBottom: 24,
  },
  presetInterestsLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: tokens.colors.foreground,
    marginBottom: 12,
  },
  spacer: {
    height: 40,
  },
  footer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 32,
    backgroundColor: tokens.colors.background,
    borderTopWidth: 1,
    borderTopColor: tokens.colors.border + '30',
  },
  backButton: {
    marginBottom: 12,
    paddingVertical: 12,
    alignItems: 'center',
  },
  backButtonText: {
    fontSize: 15,
    fontWeight: '600',
    color: tokens.colors.primary,
  },
  continueButton: {
    width: '100%',
  },
  finishButton: {
    width: '100%',
  },
});